name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      REACT_APP_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    defaults:
      run:
        working-directory: "./frontend"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build page
        run: CI='' yarn build

  test:
    name: Test on Server
    needs: build
    runs-on: ubuntu-latest
    env:
      YOUTUBE: ${{ secrets.YOUTUBE_API_KEY }}
    defaults:
      run:
        working-directory: "./backend"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run Server
        run: npm run dev & npx wait-on http://localhost:5001